"""Type stubs for the compiled beam._beam nanobind extension module.

This module is built from src/bindings.cpp via CMake/scikit-build and has
no Python source of its own, so pyright cannot infer its types from the
extension binary. These stubs mirror the bindings by hand and must be kept
in sync with python/src/bindings.cpp.
"""

from collections.abc import Callable
from typing import overload

# -- raylib value types -----------------------------------------------------

class Vector2:
    x: float
    y: float

    def __init__(self, x: float = 0.0, y: float = 0.0) -> None: ...

class Color:
    r: int
    g: int
    b: int
    a: int

    def __init__(self, r: int = 0, g: int = 0, b: int = 0, a: int = 255) -> None: ...

class Rectangle:
    x: float
    y: float
    width: float
    height: float

    def __init__(
        self,
        x: float = 0.0,
        y: float = 0.0,
        width: float = 0.0,
        height: float = 0.0,
    ) -> None: ...

class Padding:
    top: int
    left: int
    bottom: int
    right: int

    def __init__(
        self, top: int = 0, left: int = 0, bottom: int = 0, right: int = 0
    ) -> None: ...

# -- asset resource types -------------------------------------------------
#
# Only obtained via load_image/load_texture/load_font/load_sound or
# Manager's asset getters below - there is no public constructor.

class Image:
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...

class Texture:
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...

class Font:
    @property
    def base_size(self) -> int: ...
    @property
    def glyph_count(self) -> int: ...

class Sound:
    @property
    def frame_count(self) -> int: ...

def load_image(path: str) -> Image: ...
def load_texture(path: str) -> Texture: ...
def load_font(path: str) -> Font: ...
def load_sound(path: str) -> Sound: ...
def load_texture_from_image(image: Image) -> Texture: ...
def measure_text_ex(
    text: str, font_size: float, spacing: float = 1.0, font: Font | None = None
) -> Vector2: ...
def load_gui_style(path: str) -> None: ...

# -- core ---------------------------------------------------------------

class Manager:
    def has_asset(self, name: str) -> bool: ...
    @overload
    def set_asset(self, name: str, value: Image) -> None: ...
    @overload
    def set_asset(self, name: str, value: Texture) -> None: ...
    @overload
    def set_asset(self, name: str, value: Font) -> None: ...
    @overload
    def set_asset(self, name: str, value: Sound) -> None: ...
    def get_image_asset(self, name: str) -> Image: ...
    def get_texture_asset(self, name: str) -> Texture: ...
    def get_font_asset(self, name: str) -> Font: ...
    def get_sound_asset(self, name: str) -> Sound: ...
    def close(self) -> None: ...
    def closed(self) -> bool: ...
    def set_background_color(self, color: Color) -> None: ...
    def get_background_color(self) -> Color: ...
    def get_screen_width(self) -> int: ...
    def get_screen_height(self) -> int: ...
    def get_window_width(self) -> int: ...
    def get_window_height(self) -> int: ...
    def get_fps(self) -> int: ...
    def is_window_resized(self) -> bool: ...
    def get_key_pressed(self) -> int: ...
    def get_char_pressed(self) -> str: ...
    def get_mouse_x(self) -> int: ...
    def get_mouse_y(self) -> int: ...
    def is_mouse_button_down(self, button: int) -> bool: ...
    def is_mouse_button_pressed(self, button: int) -> bool: ...
    def is_mouse_button_released(self, button: int) -> bool: ...
    def is_key_down(self, key: int) -> bool: ...
    def is_key_pressed(self, key: int) -> bool: ...
    def is_key_released(self, key: int) -> bool: ...

class Node:
    def __init__(self, name: str = "Node") -> None: ...
    def init(self, manager: Manager) -> None: ...
    def update(self, delta_time: float, manager: Manager) -> None: ...
    def draw(self, manager: Manager) -> None: ...
    def set_position(self, x: float, y: float) -> None: ...
    def set_active(self, active: bool) -> None: ...
    def set_parent(self, parent: Node) -> None: ...
    def get_position(self) -> Vector2: ...
    def is_active(self) -> bool: ...
    def get_name(self) -> str: ...
    def get_parent(self) -> Node | None: ...

class Event(Node):
    def __init__(self, name: str = "Event") -> None: ...
    def add(self, child: Node) -> Event: ...
    def __lshift__(self, child: Node) -> Event: ...

class WebSocketClient:
    def __init__(self) -> None: ...
    def connect(self, uri: str) -> bool: ...
    def disconnect(self) -> None: ...
    def send_message(self, message: str) -> None: ...
    def set_message_handler(self, handler: Callable[[str], None]) -> None: ...
    def set_open_handler(self, handler: Callable[[], None]) -> None: ...
    def set_close_handler(self, handler: Callable[[], None]) -> None: ...
    def is_connected(self) -> bool: ...

# -- scene --------------------------------------------------------------

class Scene(Node):
    def __init__(self, name: str = "Scene") -> None: ...
    def add(self, child: Node) -> Scene: ...
    def __lshift__(self, child: Node) -> Scene: ...
    def on_enter(self, manager: Manager) -> None: ...
    def on_exit(self, manager: Manager) -> None: ...

class SceneManager(Node):
    def __init__(self, name: str = "SceneManager") -> None: ...
    def add(self, scene: Scene) -> SceneManager: ...
    def __lshift__(self, scene: Scene) -> SceneManager: ...
    def switch_to_scene(self, name: str, manager: Manager) -> None: ...
    def get_current_scene(self) -> Scene | None: ...
    def get_scene(self, name: str) -> Scene | None: ...

# -- objects --------------------------------------------------------------

class GameObject(Node):
    def __init__(self, name: str = "GameObject") -> None: ...

class Text(GameObject):
    def __init__(
        self,
        text: str,
        x: float,
        y: float,
        font_name: str = "default",
        font_size: float = 20.0,
        font_spacing: float = 1.0,
    ) -> None: ...
    def set_text(self, text: str) -> None: ...
    def set_color(self, color: Color) -> None: ...
    def set_font_name(self, font_name: str) -> None: ...
    def set_font_size(self, size: float) -> None: ...
    def set_font_spacing(self, spacing: float) -> None: ...
    def get_text(self) -> str: ...
    def get_color(self) -> Color: ...
    def get_font_size(self) -> float: ...

class Button(GameObject):
    def __init__(
        self,
        text: str,
        font_size: float,
        font_spacing: float,
        position: Vector2,
        size: Vector2,
        padding: Padding,
        bg: Color,
        fg: Color,
        bg_hover: Color,
        fg_hover: Color,
        font_name: str = "default",
    ) -> None: ...
    def set_text(self, text: str) -> None: ...
    def set_font_name(self, font_name: str) -> None: ...
    def set_font_size(self, size: float) -> None: ...
    def set_font_spacing(self, spacing: float) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def set_padding(self, padding: Padding) -> None: ...
    def set_bg_color(self, color: Color) -> None: ...
    def set_fg_color(self, color: Color) -> None: ...
    def set_bg_hover_color(self, color: Color) -> None: ...
    def set_fg_hover_color(self, color: Color) -> None: ...
    def get_bounds(self) -> Rectangle: ...
    def is_hovered(self) -> bool: ...
    def is_clicked(self) -> bool: ...
    def on_update(
        self, callback: Callable[[float, Button, Manager], None]
    ) -> None: ...
    def on_hover(self, callback: Callable[[Button, Manager], None]) -> None: ...
    def on_click(self, callback: Callable[[Button, Manager], None]) -> None: ...

class Input(Button):
    def __init__(
        self,
        placeholder: str,
        font_size: float,
        font_spacing: float,
        position: Vector2,
        size: Vector2,
        padding: Padding,
        bg: Color,
        fg: Color,
        bg_hover: Color,
        fg_hover: Color,
        cursor_blink_time: float = 0.5,
        font_name: str = "default",
    ) -> None: ...
    def set_content(self, content: str) -> None: ...
    def set_focused(self, focused: bool) -> None: ...
    def get_content(self) -> str: ...
    def is_focused(self) -> bool: ...
    def on_focus(self, callback: Callable[[Input, Manager], None]) -> None: ...
    def on_blur(self, callback: Callable[[Input, Manager], None]) -> None: ...

class CheckBox(GameObject):
    def __init__(
        self,
        text: str,
        position: Vector2,
        size: Vector2,
        checked: bool = False,
        bg: Color = ...,
        fg: Color = ...,
        font_name: str = "default",
        font_size: float = 20.0,
        font_spacing: float = 1.0,
    ) -> None: ...
    def set_text(self, text: str) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def set_checked(self, checked: bool) -> None: ...
    def set_bg_color(self, color: Color) -> None: ...
    def set_fg_color(self, color: Color) -> None: ...
    def set_font_name(self, font_name: str) -> None: ...
    def set_font_size(self, size: float) -> None: ...
    def set_font_spacing(self, spacing: float) -> None: ...
    def get_text(self) -> str: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def is_checked(self) -> bool: ...
    def get_bg_color(self) -> Color: ...
    def get_fg_color(self) -> Color: ...
    def get_bounds(self) -> Rectangle: ...
    def on_change(self, callback: Callable[[CheckBox, Manager], None]) -> None: ...

class Toggle(GameObject):
    def __init__(
        self,
        text: str,
        position: Vector2,
        size: Vector2,
        active: bool = False,
        bg: Color = ...,
        fg: Color = ...,
        bg_active: Color = ...,
        fg_active: Color = ...,
        font_name: str = "default",
        font_size: float = 20.0,
        font_spacing: float = 1.0,
    ) -> None: ...
    def set_text(self, text: str) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def set_active(self, active: bool) -> None: ...
    def set_bg_color(self, color: Color) -> None: ...
    def set_fg_color(self, color: Color) -> None: ...
    def set_bg_active_color(self, color: Color) -> None: ...
    def set_fg_active_color(self, color: Color) -> None: ...
    def set_font_name(self, font_name: str) -> None: ...
    def set_font_size(self, size: float) -> None: ...
    def set_font_spacing(self, spacing: float) -> None: ...
    def get_text(self) -> str: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def is_active(self) -> bool: ...
    def get_bg_color(self) -> Color: ...
    def get_fg_color(self) -> Color: ...
    def get_bg_active_color(self) -> Color: ...
    def get_fg_active_color(self) -> Color: ...
    def get_bounds(self) -> Rectangle: ...
    def on_change(self, callback: Callable[[Toggle, Manager], None]) -> None: ...

class Slider(GameObject):
    def __init__(
        self,
        position: Vector2,
        size: Vector2,
        value: float = 0.0,
        min_value: float = 0.0,
        max_value: float = 1.0,
        bg: Color = ...,
        fg: Color = ...,
        text_left: str = "",
        text_right: str = "",
    ) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def set_value(self, value: float) -> None: ...
    def set_range(self, min_value: float, max_value: float) -> None: ...
    def set_bg_color(self, color: Color) -> None: ...
    def set_fg_color(self, color: Color) -> None: ...
    def set_text_left(self, text: str) -> None: ...
    def set_text_right(self, text: str) -> None: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_value(self) -> float: ...
    def get_min_value(self) -> float: ...
    def get_max_value(self) -> float: ...
    def get_bg_color(self) -> Color: ...
    def get_fg_color(self) -> Color: ...
    def get_bounds(self) -> Rectangle: ...
    def on_change(self, callback: Callable[[Slider, Manager], None]) -> None: ...

class ProgressBar(GameObject):
    def __init__(
        self,
        position: Vector2,
        size: Vector2,
        value: float = 0.0,
        min_value: float = 0.0,
        max_value: float = 1.0,
        bg: Color = ...,
        fg: Color = ...,
        text_left: str = "",
        text_right: str = "",
    ) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def set_value(self, value: float) -> None: ...
    def set_range(self, min_value: float, max_value: float) -> None: ...
    def set_bg_color(self, color: Color) -> None: ...
    def set_fg_color(self, color: Color) -> None: ...
    def set_text_left(self, text: str) -> None: ...
    def set_text_right(self, text: str) -> None: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_value(self) -> float: ...
    def get_min_value(self) -> float: ...
    def get_max_value(self) -> float: ...
    def get_bg_color(self) -> Color: ...
    def get_fg_color(self) -> Color: ...
    def get_bounds(self) -> Rectangle: ...

class GroupBox(GameObject):
    def __init__(
        self, text: str, position: Vector2, size: Vector2, color: Color = ...
    ) -> None: ...
    def set_text(self, text: str) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def set_color(self, color: Color) -> None: ...
    def get_text(self) -> str: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_color(self) -> Color: ...
    def get_bounds(self) -> Rectangle: ...

class Line(GameObject):
    def __init__(
        self, position: Vector2, size: Vector2, text: str = "", color: Color = ...
    ) -> None: ...
    def set_text(self, text: str) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def set_color(self, color: Color) -> None: ...
    def get_text(self) -> str: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_color(self) -> Color: ...
    def get_bounds(self) -> Rectangle: ...

class DummyRec(GameObject):
    def __init__(
        self,
        text: str,
        position: Vector2,
        size: Vector2,
        bg: Color = ...,
        fg: Color = ...,
    ) -> None: ...
    def set_text(self, text: str) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def set_bg_color(self, color: Color) -> None: ...
    def set_fg_color(self, color: Color) -> None: ...
    def get_text(self) -> str: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_bg_color(self) -> Color: ...
    def get_fg_color(self) -> Color: ...
    def get_bounds(self) -> Rectangle: ...
    def on_click(self, callback: Callable[[DummyRec, Manager], None]) -> None: ...

class StatusBar(GameObject):
    def __init__(
        self,
        text: str,
        position: Vector2,
        size: Vector2,
        bg: Color = ...,
        fg: Color = ...,
    ) -> None: ...
    def set_text(self, text: str) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def set_bg_color(self, color: Color) -> None: ...
    def set_fg_color(self, color: Color) -> None: ...
    def get_text(self) -> str: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_bg_color(self) -> Color: ...
    def get_fg_color(self) -> Color: ...
    def get_bounds(self) -> Rectangle: ...
    def on_click(self, callback: Callable[[StatusBar, Manager], None]) -> None: ...

class Grid(GameObject):
    def __init__(
        self,
        position: Vector2,
        size: Vector2,
        spacing: float = 16.0,
        subdivisions: int = 4,
        color: Color = ...,
    ) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def set_spacing(self, spacing: float) -> None: ...
    def set_subdivisions(self, subdivisions: int) -> None: ...
    def set_color(self, color: Color) -> None: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_spacing(self) -> float: ...
    def get_subdivisions(self) -> int: ...
    def get_color(self) -> Color: ...
    def get_mouse_cell(self) -> Vector2: ...
    def get_bounds(self) -> Rectangle: ...

class LabelButton(GameObject):
    def __init__(
        self,
        text: str,
        position: Vector2,
        size: Vector2,
        fg: Color = ...,
        font_name: str = "default",
        font_size: float = 20.0,
        font_spacing: float = 1.0,
    ) -> None: ...
    def set_text(self, text: str) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def set_fg_color(self, color: Color) -> None: ...
    def set_font_name(self, font_name: str) -> None: ...
    def set_font_size(self, size: float) -> None: ...
    def set_font_spacing(self, spacing: float) -> None: ...
    def get_text(self) -> str: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_fg_color(self) -> Color: ...
    def get_bounds(self) -> Rectangle: ...
    def on_click(self, callback: Callable[[LabelButton, Manager], None]) -> None: ...

class ToggleGroup(GameObject):
    def __init__(
        self,
        items: list[str],
        position: Vector2,
        size: Vector2,
        active: int = 0,
        bg: Color = ...,
        fg: Color = ...,
        bg_active: Color = ...,
        fg_active: Color = ...,
        font_name: str = "default",
        font_size: float = 20.0,
        font_spacing: float = 1.0,
    ) -> None: ...
    def set_items(self, items: list[str]) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def set_active(self, active: int) -> None: ...
    def set_bg_color(self, color: Color) -> None: ...
    def set_fg_color(self, color: Color) -> None: ...
    def set_bg_active_color(self, color: Color) -> None: ...
    def set_fg_active_color(self, color: Color) -> None: ...
    def set_font_name(self, font_name: str) -> None: ...
    def set_font_size(self, size: float) -> None: ...
    def set_font_spacing(self, spacing: float) -> None: ...
    def get_items(self) -> list[str]: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_active(self) -> int: ...
    def get_bg_color(self) -> Color: ...
    def get_fg_color(self) -> Color: ...
    def get_bg_active_color(self) -> Color: ...
    def get_fg_active_color(self) -> Color: ...
    def get_bounds(self) -> Rectangle: ...
    def on_change(self, callback: Callable[[ToggleGroup, Manager], None]) -> None: ...

class ToggleSlider(GameObject):
    def __init__(
        self,
        items: list[str],
        position: Vector2,
        size: Vector2,
        active: int = 0,
        bg: Color = ...,
        fg: Color = ...,
        font_name: str = "default",
        font_size: float = 20.0,
        font_spacing: float = 1.0,
    ) -> None: ...
    def set_items(self, items: list[str]) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def set_active(self, active: int) -> None: ...
    def set_bg_color(self, color: Color) -> None: ...
    def set_fg_color(self, color: Color) -> None: ...
    def set_font_name(self, font_name: str) -> None: ...
    def set_font_size(self, size: float) -> None: ...
    def set_font_spacing(self, spacing: float) -> None: ...
    def get_items(self) -> list[str]: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_active(self) -> int: ...
    def get_bg_color(self) -> Color: ...
    def get_fg_color(self) -> Color: ...
    def get_bounds(self) -> Rectangle: ...
    def on_change(self, callback: Callable[[ToggleSlider, Manager], None]) -> None: ...

class ComboBox(GameObject):
    def __init__(
        self,
        items: list[str],
        position: Vector2,
        size: Vector2,
        active: int = 0,
        bg: Color = ...,
        fg: Color = ...,
        font_name: str = "default",
        font_size: float = 20.0,
        font_spacing: float = 1.0,
    ) -> None: ...
    def set_items(self, items: list[str]) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def set_active(self, active: int) -> None: ...
    def set_bg_color(self, color: Color) -> None: ...
    def set_fg_color(self, color: Color) -> None: ...
    def set_font_name(self, font_name: str) -> None: ...
    def set_font_size(self, size: float) -> None: ...
    def set_font_spacing(self, spacing: float) -> None: ...
    def get_items(self) -> list[str]: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_active(self) -> int: ...
    def get_bg_color(self) -> Color: ...
    def get_fg_color(self) -> Color: ...
    def get_bounds(self) -> Rectangle: ...
    def on_change(self, callback: Callable[[ComboBox, Manager], None]) -> None: ...

class SliderBar(GameObject):
    def __init__(
        self,
        position: Vector2,
        size: Vector2,
        value: float = 0.0,
        min_value: float = 0.0,
        max_value: float = 1.0,
        bg: Color = ...,
        fg: Color = ...,
        text_left: str = "",
        text_right: str = "",
    ) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def set_value(self, value: float) -> None: ...
    def set_range(self, min_value: float, max_value: float) -> None: ...
    def set_bg_color(self, color: Color) -> None: ...
    def set_fg_color(self, color: Color) -> None: ...
    def set_text_left(self, text: str) -> None: ...
    def set_text_right(self, text: str) -> None: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_value(self) -> float: ...
    def get_min_value(self) -> float: ...
    def get_max_value(self) -> float: ...
    def get_bg_color(self) -> Color: ...
    def get_fg_color(self) -> Color: ...
    def get_bounds(self) -> Rectangle: ...
    def on_change(self, callback: Callable[[SliderBar, Manager], None]) -> None: ...

class DropdownBox(GameObject):
    def __init__(
        self,
        items: list[str],
        position: Vector2,
        size: Vector2,
        active: int = 0,
        bg: Color = ...,
        fg: Color = ...,
        font_name: str = "default",
        font_size: float = 20.0,
        font_spacing: float = 1.0,
    ) -> None: ...
    def set_items(self, items: list[str]) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def set_active(self, active: int) -> None: ...
    def set_open(self, open: bool) -> None: ...
    def set_bg_color(self, color: Color) -> None: ...
    def set_fg_color(self, color: Color) -> None: ...
    def set_font_name(self, font_name: str) -> None: ...
    def set_font_size(self, size: float) -> None: ...
    def set_font_spacing(self, spacing: float) -> None: ...
    def get_items(self) -> list[str]: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_active(self) -> int: ...
    def is_open(self) -> bool: ...
    def get_bg_color(self) -> Color: ...
    def get_fg_color(self) -> Color: ...
    def get_bounds(self) -> Rectangle: ...
    def on_change(self, callback: Callable[[DropdownBox, Manager], None]) -> None: ...

class Spinner(GameObject):
    def __init__(
        self,
        text: str,
        position: Vector2,
        size: Vector2,
        value: int = 0,
        min_value: int = 0,
        max_value: int = 100,
        bg: Color = ...,
        fg: Color = ...,
        font_name: str = "default",
        font_size: float = 20.0,
        font_spacing: float = 1.0,
    ) -> None: ...
    def set_text(self, text: str) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def set_value(self, value: int) -> None: ...
    def set_range(self, min_value: int, max_value: int) -> None: ...
    def set_edit_mode(self, edit_mode: bool) -> None: ...
    def set_bg_color(self, color: Color) -> None: ...
    def set_fg_color(self, color: Color) -> None: ...
    def set_font_name(self, font_name: str) -> None: ...
    def set_font_size(self, size: float) -> None: ...
    def set_font_spacing(self, spacing: float) -> None: ...
    def get_text(self) -> str: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_value(self) -> int: ...
    def get_min_value(self) -> int: ...
    def get_max_value(self) -> int: ...
    def is_edit_mode(self) -> bool: ...
    def get_bg_color(self) -> Color: ...
    def get_fg_color(self) -> Color: ...
    def get_bounds(self) -> Rectangle: ...
    def on_change(self, callback: Callable[[Spinner, Manager], None]) -> None: ...

class ValueBox(GameObject):
    def __init__(
        self,
        text: str,
        position: Vector2,
        size: Vector2,
        value: int = 0,
        min_value: int = 0,
        max_value: int = 100,
        bg: Color = ...,
        fg: Color = ...,
        font_name: str = "default",
        font_size: float = 20.0,
        font_spacing: float = 1.0,
    ) -> None: ...
    def set_text(self, text: str) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def set_value(self, value: int) -> None: ...
    def set_range(self, min_value: int, max_value: int) -> None: ...
    def set_edit_mode(self, edit_mode: bool) -> None: ...
    def set_bg_color(self, color: Color) -> None: ...
    def set_fg_color(self, color: Color) -> None: ...
    def set_font_name(self, font_name: str) -> None: ...
    def set_font_size(self, size: float) -> None: ...
    def set_font_spacing(self, spacing: float) -> None: ...
    def get_text(self) -> str: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_value(self) -> int: ...
    def get_min_value(self) -> int: ...
    def get_max_value(self) -> int: ...
    def is_edit_mode(self) -> bool: ...
    def get_bg_color(self) -> Color: ...
    def get_fg_color(self) -> Color: ...
    def get_bounds(self) -> Rectangle: ...
    def on_change(self, callback: Callable[[ValueBox, Manager], None]) -> None: ...

class ValueBoxFloat(GameObject):
    def __init__(
        self,
        text: str,
        position: Vector2,
        size: Vector2,
        value: float = 0.0,
        bg: Color = ...,
        fg: Color = ...,
        font_name: str = "default",
        font_size: float = 20.0,
        font_spacing: float = 1.0,
    ) -> None: ...
    def set_text(self, text: str) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def set_value(self, value: float) -> None: ...
    def set_edit_mode(self, edit_mode: bool) -> None: ...
    def set_bg_color(self, color: Color) -> None: ...
    def set_fg_color(self, color: Color) -> None: ...
    def set_font_name(self, font_name: str) -> None: ...
    def set_font_size(self, size: float) -> None: ...
    def set_font_spacing(self, spacing: float) -> None: ...
    def get_text(self) -> str: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_value(self) -> float: ...
    def is_edit_mode(self) -> bool: ...
    def get_bg_color(self) -> Color: ...
    def get_fg_color(self) -> Color: ...
    def get_bounds(self) -> Rectangle: ...
    def on_change(self, callback: Callable[[ValueBoxFloat, Manager], None]) -> None: ...

class WindowBox(GameObject):
    def __init__(self, title: str, position: Vector2, size: Vector2) -> None: ...
    def add(self, child: GameObject) -> WindowBox: ...
    def __lshift__(self, child: GameObject) -> WindowBox: ...
    def set_title(self, title: str) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def get_title(self) -> str: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_bounds(self) -> Rectangle: ...
    def on_close(self, callback: Callable[[WindowBox, Manager], None]) -> None: ...

class ScrollPanel(GameObject):
    def __init__(
        self, position: Vector2, size: Vector2, content: Rectangle
    ) -> None: ...
    def add(self, child: GameObject) -> ScrollPanel: ...
    def __lshift__(self, child: GameObject) -> ScrollPanel: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def set_content(self, content: Rectangle) -> None: ...
    def set_scroll(self, scroll: Vector2) -> None: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_content(self) -> Rectangle: ...
    def get_scroll(self) -> Vector2: ...
    def get_view(self) -> Rectangle: ...
    def get_bounds(self) -> Rectangle: ...

class ListView(GameObject):
    def __init__(
        self,
        items: list[str],
        position: Vector2,
        size: Vector2,
        active: int = -1,
        bg: Color = ...,
        fg: Color = ...,
    ) -> None: ...
    def set_items(self, items: list[str]) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def set_scroll_index(self, scroll_index: int) -> None: ...
    def set_active(self, active: int) -> None: ...
    def set_bg_color(self, color: Color) -> None: ...
    def set_fg_color(self, color: Color) -> None: ...
    def get_items(self) -> list[str]: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_scroll_index(self) -> int: ...
    def get_active(self) -> int: ...
    def get_bg_color(self) -> Color: ...
    def get_fg_color(self) -> Color: ...
    def get_focus_index(self) -> int: ...
    def get_bounds(self) -> Rectangle: ...
    def on_change(self, callback: Callable[[ListView, Manager], None]) -> None: ...

class TabBar(GameObject):
    def __init__(
        self, items: list[str], position: Vector2, size: Vector2, active: int = 0
    ) -> None: ...
    def set_items(self, items: list[str]) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def set_hscroll(self, hscroll: int) -> None: ...
    def set_active(self, active: int) -> None: ...
    def get_items(self) -> list[str]: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_hscroll(self) -> int: ...
    def get_active(self) -> int: ...
    def get_focus_index(self) -> int: ...
    def get_bounds(self) -> Rectangle: ...
    def on_change(self, callback: Callable[[TabBar, Manager], None]) -> None: ...

class MessageBox(GameObject):
    def __init__(
        self,
        title: str,
        message: str,
        buttons: list[str],
        position: Vector2,
        size: Vector2,
    ) -> None: ...
    def set_title(self, title: str) -> None: ...
    def set_message(self, message: str) -> None: ...
    def set_buttons(self, buttons: list[str]) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def get_title(self) -> str: ...
    def get_message(self) -> str: ...
    def get_buttons(self) -> list[str]: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_last_button(self) -> int: ...
    def get_bounds(self) -> Rectangle: ...
    def on_button(
        self, callback: Callable[[MessageBox, Manager, int], None]
    ) -> None: ...

class TextInputBox(GameObject):
    def __init__(
        self,
        title: str,
        message: str,
        buttons: list[str],
        position: Vector2,
        size: Vector2,
    ) -> None: ...
    def set_title(self, title: str) -> None: ...
    def set_message(self, message: str) -> None: ...
    def set_content(self, content: str) -> None: ...
    def set_buttons(self, buttons: list[str]) -> None: ...
    def set_secret_view(self, secret_view: bool) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def get_title(self) -> str: ...
    def get_message(self) -> str: ...
    def get_content(self) -> str: ...
    def get_buttons(self) -> list[str]: ...
    def is_secret_view(self) -> bool: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_last_button(self) -> int: ...
    def get_bounds(self) -> Rectangle: ...
    def on_button(
        self, callback: Callable[[TextInputBox, Manager, int], None]
    ) -> None: ...

class ColorPicker(GameObject):
    def __init__(
        self, position: Vector2, size: Vector2, color: Color = ...
    ) -> None: ...
    def set_color(self, color: Color) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def get_color(self) -> Color: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_bounds(self) -> Rectangle: ...
    def on_change(self, callback: Callable[[ColorPicker, Manager], None]) -> None: ...

class ColorPanel(GameObject):
    def __init__(
        self, position: Vector2, size: Vector2, color: Color = ...
    ) -> None: ...
    def set_color(self, color: Color) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def get_color(self) -> Color: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_bounds(self) -> Rectangle: ...
    def on_change(self, callback: Callable[[ColorPanel, Manager], None]) -> None: ...

class ColorBarAlpha(GameObject):
    def __init__(
        self, position: Vector2, size: Vector2, alpha: float = 1.0
    ) -> None: ...
    def set_alpha(self, alpha: float) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def get_alpha(self) -> float: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_bounds(self) -> Rectangle: ...
    def on_change(
        self, callback: Callable[[ColorBarAlpha, Manager], None]
    ) -> None: ...

class ColorBarHue(GameObject):
    def __init__(self, position: Vector2, size: Vector2, hue: float = 0.0) -> None: ...
    def set_hue(self, hue: float) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_size(self, size: Vector2) -> None: ...
    def get_hue(self) -> float: ...
    def get_position(self) -> Vector2: ...
    def get_size(self) -> Vector2: ...
    def get_bounds(self) -> Rectangle: ...
    def on_change(self, callback: Callable[[ColorBarHue, Manager], None]) -> None: ...

class Sprite(GameObject):
    def __init__(
        self,
        manager: Manager,
        name: str,
        position: Vector2,
        bound: Rectangle,
        tint: Color = ...,
        bg: Color = ...,
    ) -> None: ...
    def set_position(self, position: Vector2) -> None: ...
    def set_bound(self, bound: Rectangle) -> None: ...
    def set_tint(self, tint: Color) -> None: ...
    def set_background_color(self, color: Color) -> None: ...
    def set_rotation(self, rotation: float) -> None: ...
    def set_scale(self, scale: float) -> None: ...
    def get_position(self) -> Vector2: ...
    def get_bound(self) -> Rectangle: ...
    def get_tint(self) -> Color: ...
    def get_background_color(self) -> Color: ...
    def get_rotation(self) -> float: ...
    def get_scale(self) -> float: ...
    def on_update(
        self, callback: Callable[[float, Sprite, Manager], None]
    ) -> None: ...
    def on_draw(self, callback: Callable[[Sprite, Manager], None]) -> None: ...

class Frame(GameObject):
    def __init__(
        self,
        name: str,
        origin: Vector2,
        bound: Rectangle,
        bg: Color = ...,
    ) -> None: ...
    def add(self, child: GameObject) -> Frame: ...
    def __lshift__(self, child: GameObject) -> Frame: ...
    def set_origin(self, origin: Vector2) -> None: ...
    def set_bound(self, bound: Rectangle) -> None: ...
    def set_background_color(self, color: Color) -> None: ...
    def set_rotation(self, rotation: float) -> None: ...
    def get_origin(self) -> Vector2: ...
    def get_bound(self) -> Rectangle: ...
    def get_background_color(self) -> Color: ...
    def get_rotation(self) -> float: ...
    def on_update(
        self, callback: Callable[[float, Frame, Manager], None]
    ) -> None: ...
    def on_draw(self, callback: Callable[[Frame, Manager], None]) -> None: ...

class TileMap(GameObject):
    @overload
    def __init__(
        self,
        name: str,
        tiles: list[list[int]],
        tile_width: int,
        tile_height: int,
        tint: Color = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        name: str,
        texture_path: str,
        tile_width: int,
        tile_height: int,
        map_width: int,
        map_height: int,
        world_x: float,
        world_y: float,
        randomizer: Callable[[int, int, float, float], int],
        tint: Color = ...,
    ) -> None: ...
    def generate_tiles(self) -> None: ...
    def load_texture(self, texture_path: str) -> bool: ...
    def set_randomizer_function(
        self, randomizer: Callable[[int, int, float, float], int]
    ) -> None: ...
    def get_tile_at(self, tile_x: int, tile_y: int) -> int: ...
    def set_tile_at(self, tile_x: int, tile_y: int, tile_index: int) -> None: ...
    def get_world_position(self) -> Vector2: ...
    def set_world_position(self, x: float, y: float) -> None: ...
    def get_map_size(self) -> Vector2: ...
    def get_texture_tile_count(self) -> Vector2: ...
    def get_total_tile_count(self) -> int: ...
    def regenerate_area(
        self, start_x: int, start_y: int, width: int, height: int
    ) -> None: ...

# -- app --------------------------------------------------------------

class App:
    def __init__(
        self,
        title: str,
        width: int,
        height: int,
        fps: int,
        fullscreen: bool = False,
        resizable: bool = False,
    ) -> None: ...
    def get_event(self) -> Event: ...
    def get_scene_manager(self) -> SceneManager: ...
    def init(self) -> None: ...
    def run(self) -> None: ...
    def get_manager(self) -> Manager: ...

# -- logger --------------------------------------------------------------

def log_info(message: str) -> None: ...
def log_warning(message: str) -> None: ...
def log_error(message: str) -> None: ...
def log_debug(message: str) -> None: ...
